### ISSUE TITLE
Support for Atmega 328 (not P)

### ISSUE THREAD

**Issue by CalinBunea** [PaulStoffregen/TimerOne#22]
Hello,
Good job on this Timer library. I think you should add support for Atmega328 (not P).
It should be a simple replace in config file 

//  Uno, Duemilanove, LilyPad, etc
//
#elif defined ( __AVR_ATmega168__ ) **|| defined ( __AVR_ATmega328__ )** || defined ( __AVR_ATmega328P__ )

Cheers,
Calin.
P.S. I write code in arduino studio for Atmega328 and then I use the microcontroller directly for different purposes (without the entire Arduino board). Also because I wanted to use all the pins of my microcontroller I haven't mounted external clock so I have the builtin clock of 8 Mhz.

P.S.S. For some reason git editor does some replacements on underscores. Anyway I think you got the idea :).

**Comment by tomaskovacik** [comment]
fixed by #29
