### ISSUE TITLE
Exactly which boards are supported for this library? ATtiny84(a) variants?

### ISSUE THREAD

**Issue by frozenspongebob** [PaulStoffregen/TimerOne#27]
Hello all,

Which particular boards does this library support? If it supported the ATtiny84(a) it would be of great help to my project.

Thanks,
Jonathan Lee
bukatea@gmail.com

**Comment by aster94** [comment]
you can see the board supported from:
https://github.com/PaulStoffregen/TimerOne/blob/master/config/known_16bit_timers.h

anyway if your board isn't there and it has a 16bit timer you could add it

**Comment by GitMoDu** [comment]
Last time I checked, ATtiny are supported, but no PWM.
