### ISSUE TITLE
[question] is this library dependent on the frequency of the cpu?

### ISSUE THREAD

**Issue by aster94** [PaulStoffregen/TimerOne#31]
hello paul,

i used this library with clickEncoder (https://github.com/soligen2010/encoder) and it worked ok on a arduino nano at 16mhz
then i moved to the final board a atmega328 running with the internal oscillator at 8Mhz and nothing worked, do you think that the issue could be related to the different clock speed?

**Comment by PaulStoffregen** [comment]
This is the wrong place to ask for project help.  Use the Arduino forum.

**Comment by aster94** [comment]
I wasn t asking for project help, i was asking about how the library works...
