### ISSUE TITLE
So the timer1 and timer3 library do not support arduino due board, right?

### ISSUE THREAD

**Issue by ApplefaceLisa** [PaulStoffregen/TimerOne#5]
I use timer1 on my arduino mega board and it works good. Now I want to transplant my code to due, it report error when I do compilation. So does it because of the library do not support due? Thank you.

**Comment by PaulStoffregen** [comment]
Correct, Arduino Due is not supported.

If anyone wishes to create Due-specific code to emulate the AVR timers, I'd be happy to merge it with this library.  But I do not have the time available to work on Due support.
