### ISSUE TITLE
Doesn't support non-avr boards?

### ISSUE THREAD

**Issue by Gargo** [PaulStoffregen/TimerOne#8]
Wemos R1 D1 + this example:
http://www.lucidarme.me/?p=5057

Or could you help at least how to change the code from this example to avoid to use TimerOne?

**Comment by PaulStoffregen** [comment]
TimerOne does work with Arduino Mega

**Comment by Gargo** [comment]
Wemos R1 D1 is not Mega. It is almost Uno clone based on ch340g + built-in esp8266. The only difference from Uno I saw is it has only one analog pin

**Comment by PaulStoffregen** [comment]
Well, if you or someone else writes the code, I'll be happy to merge it.  But I do not have this board, and even if I did, I wouldn't have the time available to write this myself.

**Comment by Gargo** [comment]
Ok about time. But you should buy it because it is so cheap that you can buy one for each shield you have

**Comment by PaulStoffregen** [comment]
Maybe you should ask the people who make and support this product to contribute code to this and other widely used libraries?
